### ISSUE TITLE
As per documentation, secret:site & secret:org is not working

### ISSUE THREAD

**Issue by carl-alberto** [pantheon-systems/terminus-secrets-manager-plugin#46]
![Screen Shot 2023-05-05 at 9 04 41 PM](https://user-images.githubusercontent.com/5098765/236465128-20fb9dac-c02b-4597-aa7c-1e5dbeee9ad8.png)

The ones that are working is

`terminus secret`

instead of

`terminus secret:site`

`terminus secret:org`

as indicated by the docs.

Not sure if this is what is supposed to be so we can update the readme doc or it is still under works

**Comment by namespacebrian** [comment]
What version of the plugin are you using?  

`terminus plugin:list`

The commands are working for me on version 1.2.0
![image](https://user-images.githubusercontent.com/87093053/236562282-fd38b6f6-667a-49a1-b319-0925d5ea4752.png)

![image](https://user-images.githubusercontent.com/87093053/236562425-fb37f2fe-3aea-4616-975d-0f317f96ca01.png)

**Comment by pantheoncarl** [comment]
Thanks @namespacebrian , I was using 1.1.1

![Screen Shot 2023-05-07 at 12 41 22 AM](https://user-images.githubusercontent.com/86540671/236636506-4ede3acf-5327-492b-96d1-e0f121f604c0.png)



was able upgrade to 1.2.0 and it is all good as documented

![Screen Shot 2023-05-07 at 12 45 23 AM](https://user-images.githubusercontent.com/86540671/236636671-bf251daf-2a7f-4af9-9f71-02bb84ca7732.png)
