### ISSUE TITLE
Odd naming convention when missing site_env

### ISSUE THREAD

**Issue by kyletaylored** [pantheon-systems/terminus-secrets-manager-plugin#55]
Just found this as odd wording in an error response. What's `siteish`?

```
Not enough arguments (missing: "siteish, name, value").
```

https://github.com/pantheon-systems/terminus-secrets-manager-plugin/blob/952a52b06f9a28baeb78427d739c1daa4866632b/src/Commands/SiteSetCommand.php#L33

**Comment by kporras07** [comment]
Tracking internally as LOPS-2255

**Comment by scottbuscemi** [comment]
Resolved in the latest release :) TY
