### ISSUE TITLE
secret:site:local-generate improvement

### ISSUE THREAD

**Issue by bwood** [pantheon-systems/terminus-secrets-manager-plugin#64]
Currently we have:
```
$ terminus secret:site:local-generate openucb-2754 --filepath=/tmp/secrets.json
 [notice] Secrets file written to: /tmp/secrets.json. Please review this file and adjust accordingly for your local usage.

$ cat secrets.json
{
    "EntityType": "sites",
    "EntityId": "66340dd3-cce6-4cf0-ad69-da67eb2442f8",
    "Secrets": {}
}
```

The developer is now obliged to dig into \PantheonSystems\CustomerSecrets\SecretList::fromJson() to discover the structure of the Secrets array.

Proposed improvement:

```
$ terminus secret:site:local-generate openucb-2754 --filepath=/tmp/secrets.json
 [notice] Secrets file written to: /tmp/secrets.json. Here is an example of values to be added to the Secrets array:

{
    "EntityType": "sites",
    "EntityId": "66340dd3-cce6-4cf0-ad69-da67eb2442f8",
    "Secrets": {
        "MY-SECRET-NAME": {
            "Value": "MY-SECRET-VALUE",
            "Type": "runtime",
            "Scopes": ["web"]
        }
    }
}

Please see: https://github.com/pantheon-systems/terminus-secrets-manager-plugin?tab=readme-ov-file#secret

# The skeleton file remains the same. The above output saves the developer time.
$ cat secrets.json
{
    "EntityType": "sites",
    "EntityId": "66340dd3-cce6-4cf0-ad69-da67eb2442f8",
    "Secrets": {}
}
```

**Comment by bwood** [comment]
Note I'm developing for Drupal 7.  Maybe if I were using pantheon_secrets.module with a modern Drupal site that module would have helped me set the secret in the local file...?

**Comment by namespacebrian** [comment]
Yes we hadn't developed a Key module integration for D7.  We started looking into creating it and a migration process due to the Lockr shutdown, but attempts to reach out to D7 customers using Lockr to ensure it will meet their needs seem to have stalled, so we might not be building that.

**Comment by greg-1-anderson** [comment]
@bwood Please set some secrets for your site first; if you do, then you will find the Secrets array populated as requested.
```
$ terminus secret:site:local-generate g1a-d9 --filepath=secrets.json
 [notice] Secrets file written to: secrets.json. Please review this file and adjust accordingly for your local usage.
ga@ocean:~/tmp/secrets-local$ cat secrets.json 
{
    "EntityType": "sites",
    "EntityId": "[REDACTED]",
    "Secrets": {
        "1this": {
            "Value": "",
            "Type": "runtime",
            "Scopes": [
                "user"
            ],
            "OrgValues": {
                "default": "secret"
            }
        },
        "55561527": {
            "Value": "",
            "Type": "runtime",
            "Scopes": [
                "user",
                "vcs"
            ],
            "OrgValues": {
                "default": "{\"access_token\":\"[REDACTED]\",\"type\":\"BEARER\",\"expires_in\":-63863561058,\"refresh_token\":\"\",\"created_at\":1727964258}"
            }
        },
        "BAZ": {
            "Value": null,
            "Type": "env",
            "Scopes": [
                "ic"
            ]
        },
...
```

Note that I inserted the [REDACTED] notes manually; these items have actual values in my file. The secret value is inserted if the secret has the scope "user", and is otherwise empty. We don't recommend giving important secrets this scope, of course, but this is available as a convenience for not-so-secret-secrets.

**Comment by bwood** [comment]
Ah. Thanks!

It didn't occur to me that this command was doing more than spitting out a simple skeleton.  Since I was in a local-dev mindset, I wasn't thinking that I would need to do anything in Pantheon's environments. 

At https://github.com/pantheon-systems/terminus-secrets-manager-plugin?tab=readme-ov-file#generate-file-for-local-development it might help others to add: This command works best if you first save a secret to Secrets Manager.
